[package]
name = "belajar-static-file"
version = "0.1.0"
authors = ["Riris Bayu <bayu.asrori@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
actix-files = "0.3"
env_logger = "0.7"